# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET on multiple Branches

on:
  push:
    branches:
      - main
      - Postman
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Itech-Attendance/Itech-Attendance.Tests
    - name: Build
      run: dotnet build Itech-Attendance/Itech-Attendance.Tests --no-restore
    - name: Test
      run: dotnet test Itech-Attendance/Itech-Attendance.Tests --no-build --verbosity normal

    # Add a step to install Newman (Postman CLI)
    - name: Install Newman
      run: npm install -g newman

    # Add a step to run Postman tests
    - name: Run Postman Tests
      run: |
        newman run Lernfeld8/Itech-Attendance/Itech-Attendance.Tests/lernfeld8.postman_collection.json